@startuml
'https://plantuml.com/object-diagram

object Edificio{
    Nombre
    Dirección
    Pisos
}
object Departamento{
    Numero
    Piso
}
object Dueño{
    Nombre
    RUT
    Correo
}
object Contrato{
    Fecha de pago
}
object Comprobante{
    Fecha de pago
    Monto
}

Comprobante "1" --> "1" Contrato : se asocia a
Comprobante "*" <-- "1" Dueño : paga
Contrato "1..*" --> "1" Dueño : tiene
Dueño "0..*" --> "1" Departamento : posee
Departamento "0..*" --> "1" Edificio : forma
@enduml
